### ISSUE TITLE
Error: Unable to resolve module react-native-webview

### ISSUE THREAD

**Issue by Zeeohn** [imnapo/react-native-cn-quill#119]
I have been trying to get the react-native-cn-quill to work in my expo-router application but it just keeps on throwing an error during the bundling process of the app. The error it throws is: 

"Error: Unable to resolve module react-native-webview from C:\Users\zeegu\Desktop\cyclekit\node_modules\react-native-cn-quill\src\editor\quill-editor.tsx: react-native-webview could not be found within the project or in these directories:
  node_modules\react-native-cn-quill\node_modules
  node_modules
  4 |   WebViewMessageEvent,
  5 |   WebViewProps,
> 6 | } from 'react-native-webview';
    |         ^
  7 | import {
  8 |   View,
  9 |   Text,
    at ModuleResolver.resolveDependency (C:\Users\zeegu\Desktop\cyclekit\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:139:15)
    at DependencyGraph.resolveDependency (C:\Users\zeegu\Desktop\cyclekit\node_modules\metro\src\node-haste\DependencyGraph.js:277:43)  
    at Object.resolve (C:\Users\zeegu\Desktop\cyclekit\node_modules\metro\src\lib\transformHelpers.js:169:21)
    at Graph._resolveDependencies (C:\Users\zeegu\Desktop\cyclekit\node_modules\metro\src\DeltaBundler\Graph.js:473:35)
    at Graph._processModule (C:\Users\zeegu\Desktop\cyclekit\node_modules\metro\src\DeltaBundler\Graph.js:261:38)

**Comment by NikunjB12** [comment]
install the dependency react-native-webview
